import 'package:get/get_navigation/get_navigation.dart';

class MyLocal implements Translations{
  @override
  Map<String, Map<String, String>> get keys => {
    'en' :{
      "loginHead": "User Login",
      "emailAddress": "Email Address",
      "password": "Password",
      "emailAddressError": "please enter your email address",
      "passwordError": "please enter your account password",
      "donNotHaveAccount": "Don't have an account?",
      "registerNow": "new account",
      "registerHead": "Create New Account",
      "registerUserHead": "Create User Account",
      "registerDoctorHead": "Create Doctor Account",
      "fullName": "Full Name",
      "specialization": "Specialization",
      "nationalId": "National Id",
      "government": "Government",
      "mobileNumber": "Mobile Number",
      "address": "Address",
      "confirmPassword": "Confirm Password",
      "fullNameError": "please enter your full name",
      "specializationError": "please enter your specialization",
      "nationalIdError": "please enter your national id",
      "mobileNumberError": "please enter your mobile number",
      "addressError": "please enter your address",
      "confirmPasswordError": "please re-enter password for confirmation",
      "myRequests": "My requests",
      "orderNumber": "order number",
      "requestType": "request type",
      "submissionDate": "Submission date",
      "orderStatus": "Order status",
      "departmentName": "Department Name",
      "responseDate": "response date",
      "attendanceDate": "Attendance date",
      "comments": "comments",
      "print": "Print",
      "logout": "Logout",
      "browse": "Browse",
      "noDataFound": "No data Found",
      "noRequests": "No requests...",
      "home": "Home",
      "logoutConfirmation": "Are you sure you want to logout?",
      "cancel": "Cancel",
      "yes": "Yes",
      "loginError": "email or password is wrong, please make sure and try again",
      "areYouDoctor": "Are you a doctor?",
      "changeLanguage": "Change language",
      "changeTheme": "Change theme",
      "darkMode": "Dark Mode",
      "lightMode": "Light Mode",
      "arabic": "Arabic",
      "english": "English",
      "profile": "Profile",
      "search": "Search",
      "setting": "Setting",
      "aboutUs": "About Us",
      "contactUs": "Contact Us",
      "faq": "FAQ",
      "searchPage": "Search Page",
      "fakeName": "Salm Salah Salm",
      "fakeDoctor": "Consultant general surgery at Cairo University",
      "fakeAddress": "Nasr City - Cairo",
      "fakeHospital": "Al Noor Hospital",
      "fakeHeadPrice": "Consultation price",
      "pound": "Pound",
      "fakeReservation": "Consultation booking",
      "review": "Rate",
      "fakeAdvisor": "Advisor",
      "experience": "Experienced",
      "availableToday": "Available today",
      "fakeAvailableToday": "Appointments available today",
      "fakeReservationDetails": "Book a Consultation",
      "march": "March",
      "cart": "Cart",
      "categories": "Categories",
      "sale": "SALE",
      "egp": "EGP",
      "removeFromCart": "Remove from cart",
      "addToCart": "Add To Cart",
      "pleaseLoginToAddOrRemoveCart": "please login to add or remove from cart",
      "remove": "Remove",
      "areYouSureToRemove": "Are you sure to remove",
      "outStock": "Out of stock",
      "inStock": "in stock",
      "relatedCategories": "related Categories",
      "addSomeProductsToCart": "Add some products to cart",
      "subtotal": "Subtotal",
      "checkout": "Checkout",
      "total": "Total",
      "thereNoProducts": "Sorry, there are no products",
    },


    'ar' :{
      "loginHead": "تسجيل الدخول",
      "emailAddress": "البريد الإلكتروني",
      "password": "كلمة المرور",
      "emailAddressError": "من فضلك أدخل البريد الإلكتروني الخاص بك",
      "passwordError": "من فضلك أدخل كلمة المرور الخاصة بحسابك",
      "donNotHaveAccount": "ليس لديك حساب؟",
      "registerNow": "سجل حساب الآن",
      "registerUserHead": "تسجيل مستخدم جديد",
      "registerDoctorHead": "تسجيل دكتور جديد",
      "registerHead": "تسجيل مستخدم جديد",
      "fullName": "الاسم بالكامل",
      "specialization": "التخصص",
      "nationalId": "الرقم القومى",
      "government": "المحافظه",
      "mobileNumber": "رقم الموبايل",
      "address": "العنوان",
      "confirmPassword": "تأكيد كلمة المرور",
      "fullNameError": "من فضلك أدخل اسمك بالكامل",
      "specializationError": "من فضلك أدخل التخصص",
      "nationalIdError": "من فضلك أدخل رقمك القومى",
      "mobileNumberError": "من فضلك أدخل رقم الموبايل الخاص بك ",
      "addressError": "من فضلك أدخل عنوانك",
      "confirmPasswordError": "من فضلك أدخل أعد إدخال كلمة المرور للتأكيد",
      "myRequests": "طلباتى",
      "orderNumber": "رقم الطلب",
      "requestType": "نوع الطلب",
      "submissionDate": "تاريخ التقديم",
      "orderStatus": "حالة الطلب",
      "departmentName": "اسم القسم",
      "responseDate": "تاريخ الرد",
      "attendanceDate": "موعد الحضور",
      "comments": "تعليقات",
      "print": "طباعة",
      "logout": "تسجيل الخروج",
      "browse": "تصفح",
      "noDataFound": "لا يوجد معلومات",
      "noRequests": "لا يوجد طلبات...",
      "home": "الرئيسية",
      "logoutConfirmation": "هل أنت متأكد من تسجيل الخروج؟",
      "cancel": "إلغاء",
      "yes": "نعم",
      "loginError": "البريد الإلكتروني أو كلمة المرور غير صحيحين٬ برجاء التأكد و إعادة المحاولة",
      "areYouDoctor": "هل أنت دكتور؟",
      "changeLanguage": "تغيير اللغة",
      "changeTheme": "تغيير الوضعية",
      "darkMode": "الوضع الداكن",
      "lightMode": "وضع الضوء",
      "arabic": "اللغه العربية",
      "english": "اللغه الانجليزية",
      "profile": "الملف الشخصي",
      "search": "بحث",
      "setting": "الأعدادات",
      "aboutUs": "معلومات عنا",
      "contactUs": "اتصل بنا",
      "faq": "التعليمات",
      "searchPage": "صفحة البحث",
      "fakeName": "سالم صلاح سالم",
      "fakeDoctor": "استشارى جراحة عامة بجامعة القاهرة",
      "fakeAddress": "مدينة نصر - القاهرة",
      "fakeHospital": "مستشفي النور التخصصى",
      "fakeHeadPrice": "سعر الأستشارة",
      "pound": "جنية",
      "fakeReservation": "حجز إستشارة",
      "review": "تقيم",
      "fakeAdvisor": "إستشارى",
      "experience": "ذو خبرة",
      "availableToday": "متاح اليوم",
      "fakeAvailableToday": "المواعيد المتاحة اليوم",
      "fakeReservationDetails": "إحجز إستشارة",
      "march": "مارس",
      "categories": "الأقسام",
      "cart": "السلة",
      "sale": "عرض",
      "egp": "جنيه",
      "removeFromCart": "إزالة من السلة",
      "addToCart": "أضف إلى السلة",
      "pleaseLoginToAddOrRemoveCart": "الرجاء تسجيل الدخول لإضافة أو إزالة من سلة التسوق",
      "remove": "إزالة",
      "areYouSureToRemove": "هل أنت متأكد من إزالة",
      "outStock": "غير متوفر فى المخزن",
      "inStock": "متوفر فى المخزن",
      "relatedCategories": "أقسلم ذات صلة",
      "addSomeProductsToCart": "أضف بعض المنتجات إلى عربة التسوق",
      "subtotal": "المجموع الفرعي",
      "checkout": "الدفع",
      "total": "المبلغ الإجمالي",
      "thereNoProducts": "آسف لا يوجد منتجات"
    },
  };

}